code --install-extension alphabotsec.vscode-eclipse-keybindings 
code --install-extension bierner.emojisense 
code --install-extension bierner.github-markdown-preview 
code --install-extension bierner.markdown-checkbox 
code --install-extension bierner.markdown-emoji 
code --install-extension bierner.markdown-mermaid 
code --install-extension bierner.markdown-preview-github-styles 
code --install-extension bierner.markdown-yaml-preamble 
code --install-extension bpruitt-goddard.mermaid-markdown-syntax-highlighting 
code --install-extension codespaces-contrib.codeswing 
code --install-extension cweijan.vscode-office 
code --install-extension dbaeumer.vscode-eslint 
code --install-extension deepred.daily-anime 
code --install-extension donjayamanne.jupyter 
code --install-extension eamodio.gitlens 
code --install-extension ecmel.vscode-html-css 
code --install-extension EFanZh.graphviz-preview 
code --install-extension esbenp.prettier-vscode 
code --install-extension felipecaputo.git-project-manager 
code --install-extension foam.foam-vscode 
code --install-extension gamedilong.anes 
code --install-extension gera2ld.markmap-vscode 
code --install-extension giscafer.leek-fund 
code --install-extension GitHub.github-vscode-theme 
code --install-extension goobyter.vscode-weixin-read 
code --install-extension Gruntfuggly.todo-tree 
code --install-extension hancel.google-translate 
code --install-extension hediet.vscode-drawio 
code --install-extension ionutvmi.reg 
code --install-extension jebbs.plantuml 
code --install-extension koppt.vscode-view-in-browser 
code --install-extension kortina.vscode-markdown-notes 
code --install-extension LeetCode.vscode-leetcode 
code --install-extension lidandan.PictureHandler 
code --install-extension lonefy.vscode-JS-CSS-HTML-formatter 
code --install-extension mdickin.markdown-shortcuts 
code --install-extension mohd-akram.vscode-html-format 
code --install-extension ms-azuretools.vscode-docker 
code --install-extension MS-CEINTL.vscode-language-pack-zh-hans 
code --install-extension ms-python.python 
code --install-extension ms-python.vscode-pylance 
code --install-extension ms-toolsai.jupyter 
code --install-extension ms-vscode-remote.remote-wsl 
code --install-extension mushan.vscode-paste-image 
code --install-extension novenn.random-something 
code --install-extension paulmolluzzo.convert-css-in-js 
code --install-extension philipbe.theme-gray-matter 
code --install-extension RandomFractalsInc.vscode-data-preview 
code --install-extension redhat.java 
code --install-extension redhat.vscode-commons 
code --install-extension redhat.vscode-xml 
code --install-extension runningcoder.js-snippets 
code --install-extension saekiraku.rainbow-fart 
code --install-extension sandcastle.vscode-open 
code --install-extension SDTTTTT.bangumiopen 
code --install-extension skn0tt.markdown-link-expander 
code --install-extension Souche.vscode-mindmap 
code --install-extension Spades.vs-picgo 
code --install-extension takanotume24.pdf 
code --install-extension tchayen.markdown-links 
code --install-extension techer.open-in-browser 
code --install-extension TheEdgesofBen.punk-runner 
code --install-extension tkrkt.linenote 
code --install-extension tomoki1207.pdf 
code --install-extension VisualStudioExptTeam.vscodeintellicode 
code --install-extension voldikss.vscode-translator 
code --install-extension vscjava.vscode-java-debug 
code --install-extension vscjava.vscode-java-dependency 
code --install-extension vscjava.vscode-java-pack 
code --install-extension vscjava.vscode-java-test 
code --install-extension vscjava.vscode-maven 
code --install-extension vsls-contrib.codetour 
code --install-extension vsls-contrib.gistfs 
code --install-extension whosydd.typora-open 
code --install-extension xlthu.Pangu-Markdown 
code --install-extension YRM.zhihu 
code --install-extension YXL.cloudmusic 
code --install-extension yzane.markdown-pdf 
code --install-extension yzhang.markdown-all-in-one 
code --install-extension zaaack.markdown-editor 
